title: "M. Daniel Mehus"
description: ""
email: ""
url: https://danielmehus.github.io
baseurl: ""          # keep empty for user sites
theme: minima

# Pages to show in the dropdown menu
header_pages:
  - about.md
  - work.md
  - writing.md
  - contact.md
